---
title: "Dashboard of College Costs"
output: 
  flexdashboard::flex_dashboard:
    theme:
      version: 5
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
    

runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(quantreg)
library(tidyverse)
library(dlookr)
library(broom)
library(DataExplorer)
library(here)
library(ggdist)
library(shiny)
library(gt)

custom_palette <- c("#192D45", "#748CDB", "#163B88", "#C1DFF9")

data <- read_csv(here("Dados/nces330_20.csv"), col_types = "iccccd") %>%
  rename(cost = "Value") %>%
  rename_with(.fn = str_to_lower)

summarize_data <- function(data){
  data %>%
    summarize(mean_cost   = mean(cost),
              total_cost  = sum(cost),
              n           = n(),
              std_error   = sd(cost) / sqrt(n()),
              upper_bound = mean_cost + 1.96 * std_error,
              lower_bound = mean_cost - 1.96 * std_error,
              .groups     = "drop")
}

## 
##

```

```{css, echo=FALSE}
.chart-shim {
      overflow: auto;
}

body {
  background-image: linear-gradient(to bottom, #367feb, #3870f2, #4c5df5, #6744f3, #8312eb);
}

div#section-column-1 {
  box-shadow: 3px 3px 5px #abf;
  border-radius: 0px 0px 10px 10px;
}

a.tab-item {
  color: #4c5df5;
}

```


# Data Analysis

## Column {.sidebar data-width="200"}

```{r}
selectInput("cat_var",
            label = "Choose a variable", 
            choices = c("Type" = "type",
                        "Length" = "length",
                        "Expense" = "expense"), 
            selected = "type")
```

## Column {.tabset data-width="650"}

### Variable Distribution

```{r}
renderPlot({
  data %>% 
  ggplot(aes(cost, .data[[input$cat_var]], fill = .data[[input$cat_var]])) +
  stat_halfeye(aes(fill = .data[[input$cat_var]]),
                       adjust = 2.2, 
                       point_color = NA, 
                       justification = -0.1) +
  geom_boxplot(width = 0.11, 
               color = "black",
               alpha = 0.5,
               outlier.color = NA,
               size = 0.8, 
               show.legend = FALSE) +
  stat_summary(fun = "sd", geom = "text",
               aes(label = after_stat(str_c("SD: ", round(x)))),
               hjust = 3, vjust = 0, fontface = "bold", color = "black") +
  scale_x_continuous(labels = scales::dollar,
                     n.breaks = 6) +
  scale_fill_manual(values = custom_palette) +
  labs(x='',y='', fill='') + 
  ggthemes::theme_hc()
})


```

### Evolution in Time

```{r}
renderPlot({
  data %>% 
  group_by(year, .data[[input$cat_var]]) %>% 
  summarize_data() %>% 
  ggplot(aes(year, mean_cost, color = .data[[input$cat_var]])) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 3) +
  geom_ribbon(aes(ymin = lower_bound,
                  ymax = upper_bound, 
                  fill = .data[[input$cat_var]]), 
              alpha = 0.1) +
  scale_x_continuous(breaks = 2013:2021) +
  scale_y_continuous(labels = scales::dollar) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  theme(legend.position = "bottom") +
  labs(x='', y='',
       title = "Mean College Costs") +
  ggthemes::theme_hc()
})
```

### Period Variation

```{r}
plots <- data %>% 
  group_by(state, year) %>% 
  summarize_data() %>% 
  select(state, total_cost) %>% 
  nest(data = -state) %>% 
  mutate(data = map(data, \(x) pull(x)))
  # nest(data = -(state)) %>% 
  # mutate(data = map(data, \(x) {
  #   x %>%
  #     group_by(year) %>%
  #     summarize_data() %>% 
  #     pull(total_cost)
  # }
  # ))

my_cols <- colorRampPalette(c("#c993fa", "#8312eb"))

data %>%
  group_by(year, state) %>%
  summarize_data() %>%
  #summarize(total_cost = sum(cost),
  #          .groups = "drop") %>%
  arrange(state, year) %>%
  filter(year %in% c(2013, 2021)) %>%
  pivot_wider(id_cols = c(state),
              names_from = year,
              values_from = total_cost) %>%
  mutate(diff_perc = ((`2021` / `2013`) - 1) * 100) %>%
  arrange(desc(diff_perc)) %>% 
  inner_join(plots, by = "state") %>% 
  gt() %>%
  gtExtras::gt_plt_sparkline(data, 
                             fig_dim = c(7,30),
                             label = FALSE) %>% 
  tab_header(title = "Cost variation in all U.S States",
             subtitle = "2013-2021") %>% 
  cols_label(state = "State",
             diff_perc = "% Change",
             data = "Trend") %>%
  fmt_currency(columns = c(`2013`, `2021`),
               use_subunits = FALSE) %>%
  fmt_percent(columns = "diff_perc",
              scale_values = FALSE) %>% 
  data_color(columns = c(`2013`, `2021`),
             palette = my_cols(35),
             method = "numeric")

```

# Regression Analysis

```{r}
lm_mod <- lm(cost ~ length + expense + type,
             data = data)
lm_coefs <- tidy(lm_mod, conf.int = TRUE) %>%
  slice(-1) %>%
  select(term, estimate, conf.low, conf.high)

qr <- rq(cost ~ length + expense + type,
         data = data,
         tau = seq(0.1, 0.9, 0.1))

models <- tidy(qr) %>%
  mutate(model = "qr") %>%
  filter(!str_detect(term, "Inter")) %>%
  bind_rows(lm_coefs %>%
              select(term, estimate, conf.low, conf.high) %>%
              mutate(model = "lm")) 
renderPlot({
  models %>%
  ggplot(aes(tau, estimate)) +
  facet_wrap(vars(term),
             scales = "free", 
             ncol = 2) +
  geom_point(size = 1.8, 
             color = custom_palette[3]) +
  geom_line(linewidth = 1,
            color = custom_palette[3]) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),
              alpha = 0.25,
              color = custom_palette[2], 
              fill = custom_palette[2]) +
  geom_hline(data = models %>% filter(model == "lm", str_detect(term, "length")),
             aes(yintercept = estimate), lty = 2, size = 1, color = custom_palette[3]) +
  geom_hline(data = models %>% filter(model == "lm", str_detect(term, "expense")),
             aes(yintercept = estimate), lty = 2, size = 1, color = custom_palette[3]) +
  geom_hline(data = models %>% filter(model == "lm", str_detect(term, "In-State")),
             aes(yintercept = estimate), lty = 2, size = 1, color = custom_palette[3]) +
  geom_hline(data = models %>% filter(model == "lm", str_detect(term, "Out-of-State")),
             aes(yintercept = estimate), lty = 2, size = 1, color = custom_palette[3]) +
  scale_x_continuous(breaks = seq(0,1,0.1)) +
  scale_y_continuous(labels = scales::dollar_format(scale = 1e-3, suffix = "K")) +
  labs(x='Quantile', y='Estimate',
       title = "Quantitle Regression Plot",
       subtitle = "Dashed line indicates linear regression coefficient") +
  ggthemes::theme_hc() +
  theme(
    strip.background = element_rect(fill = custom_palette[4], linewidth = 1),
    strip.text = element_text(face = "bold", color = custom_palette[1])
    )
})

```

